[package]
name = "rustgression"
version = "0.2.0-alpha.4"
edition = "2021"
authors = ["connect0459 <connect0459@gmail.com>"]
description = "Fast OLS and TLS regression using Rust backend"
readme = "README.md"
license = "MIT"

[lib]
name = "rustgression"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
numpy = "0.19"
ndarray = "0.15"
nalgebra = "0.32"
