[package]
name = "rustgression"
version = "0.0.1"
edition = "2021"

[lib]
name = "rustgression"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
numpy = "0.19"
ndarray = "0.15"
ndarray-linalg = { version = "0.16", features = ["netlib"] }
