"""Type stubs for rustgression.regression.ols_multi module."""

import numpy as np
from numpy.typing import NDArray

from .base import OlsMultiRegressionParams

class OlsMultiRegressor:
    """Class for multiple Ordinary Least Squares (OLS) regression."""

    x: NDArray[np.floating]
    y: NDArray[np.floating]
    _coefficients: NDArray[np.floating]
    _r_squared: float
    _f_statistic: float
    _p_value: float

    def __init__(self, x: NDArray[np.floating], y: NDArray[np.floating]) -> None: ...
    def _fit(self) -> None: ...
    def predict(self, x: NDArray[np.floating]) -> NDArray[np.floating]: ...
    def coefficients(self) -> NDArray[np.floating]: ...
    def intercept(self) -> float: ...
    def r_squared(self) -> float: ...
    def f_statistic(self) -> float: ...
    def p_value(self) -> float: ...
    def get_params(self) -> OlsMultiRegressionParams: ...
    def __repr__(self) -> str: ...
