"""Type stubs for rustgression.regression.tls module."""

from typing import NoReturn

import numpy as np
from numpy.typing import NDArray

from .base import BaseRegressor, TlsRegressionParams

class TlsRegressor(BaseRegressor[TlsRegressionParams]):
    """Class for calculating Total Least Squares (TLS) regression."""

    def __init__(self, x: NDArray[np.floating], y: NDArray[np.floating]) -> None: ...
    def _fit(self) -> None: ...
    def slope(self) -> float: ...
    def intercept(self) -> float: ...
    def r_value(self) -> float: ...
    def r_squared(self) -> float: ...
    def p_value(self) -> float: ...
    def stderr(self) -> float: ...
    def intercept_stderr(self) -> float: ...
    @staticmethod
    def _interval_not_supported(method_name: str) -> NoReturn: ...
    def confidence_interval(self, alpha: float = ...) -> NoReturn: ...
    def prediction_interval(
        self, x_new: NDArray[np.floating], alpha: float = ...
    ) -> NoReturn: ...
    def get_params(self) -> TlsRegressionParams: ...
