name: Deploy to PyPI

on:
  release:
    types: [published]

jobs:
  deploy-to-pypi:
    if: github.event_name == 'release'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Windows環境でのBLASライブラリのセットアップ
      - name: Setup BLAS (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y mingw
          choco install -y msys2
          refreshenv

      - name: Check versions
        shell: bash
        run: |
          GIT_VERSION=${GITHUB_REF#refs/tags/v}
          CARGO_VERSION=$(grep '^version = ' Cargo.toml | cut -d '"' -f2)
          PYPROJECT_VERSION=$(grep '^version = ' pyproject.toml | cut -d '"' -f2)
          if [ "$GIT_VERSION" != "$CARGO_VERSION" ] || [ "$GIT_VERSION" != "$PYPROJECT_VERSION" ]; then
            echo "Version mismatch!"
            echo "Git tag: $GIT_VERSION"
            echo "Cargo.toml: $CARGO_VERSION"
            echo "pyproject.toml: $PYPROJECT_VERSION"
            exit 1
          fi
          echo "Versions match: $GIT_VERSION"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Windowsビルド用の環境変数設定
      - name: Set Windows environment
        if: matrix.os == 'windows-latest'
        run: |
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
          echo "OPENBLAS_DIR=C:/msys64/mingw64" >> $GITHUB_ENV
        shell: bash

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.os == 'windows-latest' && 'x64' || 'x86_64' }}
          args: --release --strip
          manylinux: ${{ matrix.os == 'ubuntu-latest' && 'auto' || 'off' }}
          container: off

      - name: Install twine
        run: pip install twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload target/wheels/*
