name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  # Step 1: 全プラットフォームでビルド
  build:
    runs-on: ${{ matrix.os }}
    if: github.event.release.target_commitish == 'main'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # バージョン確認ステップ
      - name: Check version consistency
        shell: bash
        run: |
          ./scripts/version-check.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # Linux環境のセットアップ（Ubuntu）
      - name: Setup Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      # macOS環境のセットアップ
      - name: Setup macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake

      # Windows環境のセットアップ
      - name: Setup Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake -y

      # ホイールをビルド
      - name: Build wheels
        shell: bash
        run: |
          echo "Building wheels for ${{ matrix.os }}..."
          pip install maturin

          # ホイールを明示的にビルド
          maturin build --release

          # ビルドされたホイールの場所を確認
          echo "Built wheels:"
          ls -la target/wheels/ || echo "No wheels directory found"

      # ビルドしたホイールをアーティファクトとしてアップロード
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: target/wheels/*.whl
          retention-days: 1

  # Step 2: 全てのビルドが成功した後に一括パブリッシュ
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist/
          merge-multiple: true

      - name: Verify downloaded wheels
        run: |
          echo "Downloaded wheels:"
          ls -la dist/
          echo "Wheel count: $(ls -1 dist/*.whl | wc -l)"

      - name: Publish to PyPI
        run: |
          pip install twine

          # 環境変数を設定
          export TWINE_USERNAME=__token__
          export TWINE_PASSWORD=${{ secrets.PYPI_API_TOKEN }}

          # 全てのホイールを一括アップロード
          echo "Uploading all wheels to PyPI:"
          twine upload dist/*.whl
