name: Release to PyPI

on:
  release:
    types: [published]

run-name: Release to PyPI ${{ github.event.release.tag_name }}

jobs:
  # Step 1: Version consistency check
  version-check:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Check version consistency
        shell: bash
        run: |
          # Extract version from release tag (v0.0.1 -> 0.0.1)
          VERSION=${GITHUB_REF#refs/tags/v}
          ./scripts/version-check.sh "$VERSION"

  # Step 2: Build wheels for all platforms
  build:
    needs: version-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version-file: '.python-version'

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1.15.1
        # rust-toolchain.tomlを自動的に読み込んでツールチェーンをセットアップ

      # Linux環境のセットアップ（Ubuntu）
      - name: Setup Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          if command -v cmake &> /dev/null; then
            echo "cmake is already installed"
            cmake --version
          else
            sudo apt-get update
            sudo apt-get install -y cmake
          fi

      # macOS環境のセットアップ
      - name: Setup macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          if command -v cmake &> /dev/null; then
            echo "cmake is already installed"
            cmake --version
          else
            brew install cmake
          fi

      # Windows環境のセットアップ
      - name: Setup Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          if (Get-Command cmake -ErrorAction SilentlyContinue) {
            Write-Output "cmake is already installed"
            cmake --version
          } else {
            choco install cmake -y
          }

      # ホイールをビルド
      - name: Build wheels
        shell: bash
        run: |
          echo "Building wheels for ${{ matrix.os }}..."
          pip install maturin

          # ホイールを明示的にビルド
          maturin build --release

          # ビルドされたホイールの場所を確認
          echo "Built wheels:"
          ls -la target/wheels/ || echo "No wheels directory found"

      # ビルドしたホイールをアーティファクトとしてアップロード
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: wheels-${{ matrix.os }}
          path: target/wheels/*.whl
          retention-days: 1

  # Step 3: Publish all wheels to PyPI after successful builds
  publish:
    needs: [version-check, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v4
        with:
          pattern: wheels-*
          path: dist/
          merge-multiple: true

      - name: Verify downloaded wheels
        run: |
          echo "Downloaded wheels:"
          ls -la dist/
          echo "Wheel count: $(ls -1 dist/*.whl | wc -l)"

      - name: Publish to PyPI
        run: |
          pip install twine

          # 環境変数を設定
          export TWINE_USERNAME=__token__
          export TWINE_PASSWORD=${{ secrets.PYPI_API_TOKEN }}

          # 全てのホイールを一括アップロード
          echo "Uploading all wheels to PyPI:"
          twine upload dist/*.whl
