name: Test and Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch: # 手動実行も可能にする

jobs:
  test-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # 一つの環境のビルド失敗で全体が止まらないようにする
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # Linux環境のセットアップ（Ubuntu）
      - name: Setup Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      # Windows環境のセットアップ
      - name: Setup Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          # Windowsでは基本的なツールのみ必要
          choco install cmake -y

      # ビルドしてインストール (maturin developを使用)
      - name: Build and install with maturin develop
        shell: bash
        run: |
          # 環境情報を表示
          echo "Building environment info:"
          python --version
          rustc --version

          # 仮想環境を認識できるようにする
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            # Windowsでの処理
            export VIRTUAL_ENV=$(python -c "import sys; print(sys.prefix)")
          else
            # Linux/Macでの処理
            export VIRTUAL_ENV=$(python -c "import sys; print(sys.prefix)")
          fi
          echo "Setting VIRTUAL_ENV=$VIRTUAL_ENV"

          # maturinをインストール
          pip install maturin

          # maturin developでビルド・インストール
          VIRTUAL_ENV=$VIRTUAL_ENV maturin develop

          # インストールされたモジュールを確認
          echo "インストールされたパッケージ:"
          pip list

          # Pythonモジュールパスとモジュール構造を確認
          python -c "import sys; print('Python module paths:'); [print(p) for p in sys.path]"
          python -c "import rustgression; print('Rustgression module location:', rustgression.__file__)"

      # パッケージのインポートテスト
      - name: Test import
        shell: bash
        run: |
          # バージョン情報だけでインポートテスト
          python -c "import rustgression; print(f'Successfully imported rustgression {rustgression.__version__}')" || {
            echo "Failed to import rustgression"
            exit 1
          }

          # 簡単なクラスのインスタンス化テスト
          python -c "
          import rustgression
          import numpy as np
          try:
              # 簡単なデータを作成
              x = np.array([1.0, 2.0, 3.0])
              y = np.array([2.0, 4.0, 6.0])
              
              # OLSレグレッサーを試す
              print('Creating OLS regressor...')
              regressor = rustgression.OlsRegressor(x, y)
              params = regressor.get_params()
              print(f'OLS slope: {params.slope}')
              
              # TLSレグレッサーも試す
              print('Creating TLS regressor...')
              tls = rustgression.TlsRegressor(x, y)
              tls_params = tls.get_params()
              print(f'TLS slope: {tls_params.slope}')
              
              print('All classes imported and tested successfully!')
          except Exception as e:
              print(f'Error during class testing: {e}')
              import traceback
              traceback.print_exc()
              exit(1)
          " || {
            echo "Failed to import and test rustgression classes"
            exit 1
          }

      # テストの実行
      - name: Run tests
        shell: bash
        run: |
          # インポートできる場合だけテストを実行
          python -c "import rustgression" && python -m pytest || {
            echo "Skipping tests due to import failure"
          }

      # ビルド成果物をアップロード（PRとワークフロー手動実行時のみ）
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: target/wheels/*.whl
          retention-days: 7